spring:
  application:
    name: demo

  datasource:
    url: jdbc:mysql://localhost:3306/learn_springboot
    username: root
    password: csepjt

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

server:
  port: 8081